### ISSUE TITLE
KeyError: 'Summon' 

### ISSUE THREAD

**Issue by Tyy1233** [RackunSec/Summon#1]
Getting a error on command 'python3 summon.py install demon -u (non-root username)
Traceback:
file "opt/demon/summon.py", line 153 in <module> main()
file "Same^", line 48 in main repo=Repo()
file "opt/demon/classes/Repo.py" , line 24 in __init__ self.summon_path=self.get_install_path()
file"same^", line 128, in get_install_path summon_path=config['SUMMON']['summon_path']
file "/usr/lib/python3.9/configparser.py", line 960, in __getitem__ raise keyError

Command for python3 summon.py works fine

**Comment by RackunSec** [comment]
My first issue! Woohoo! Thank you for your submission! Can you please show me the output of `cat /etc/demon/summon.conf ` ? It looks to me (from your paste) that file is mangled somehow.

**Comment by RackunSec** [comment]
Closing issue for now due to no response. 😞
