### ISSUE TITLE
'Checking internet connectivity' then nothing

### ISSUE THREAD

**Issue by Haquor** [RackunSec/Summon#3]
Installed as per the instructions
Followed [the video](https://www.youtube.com/watch?v=CspmyGp7LbA) exactly
The only thing I had to do was add trusted-hosts to the PIP global config.
After that, setup.sh worked and installed modules fine...

When running `python3 summon.py install demon -u nonsudoaccount`
I receive only "Checking internet connectivity" then the script exits.

Internet works and packages can be installed, so I'm leaning toward this being an issue with requests or something.
Can anyone help out? Would really love to check out DemonLinux :)

**Comment by RackunSec** [comment]
Hello and thank you for reporting this. I actually cannot replicate the issue you are having. I have a snapshot of my VM taken after adding the douglas user and providing him access. So each time I do major updates, I revert back to that and re-clone the repo. Which ISO did you use to do your Debian base installation? I never added trusted hosts to PIP before. Is that something PIP told you to do? Thank you again. I hope we can figure this out.

-- edit
I just performed a snapshot revert and cloned this repo and it worked again :S If you don't even see "Summoning the DEMON" in your terminal, then files/install_modules/demon.py is not even being called. It gets called using `importlib.import_module()`. My version (from the Debian netISO on demonlinux.com) is `importlib-1.0.4` Can you please post your version?

**Comment by Haquor** [comment]
> Hello and thank you for reporting this. I actually cannot replicate the issue you are having. I have a snapshot of my VM taken after adding the douglas user and providing him access. So each time I do major updates, I revert back to that and re-clone the repo. Which ISO did you use to do your Debian base installation? I never added trusted hosts to PIP before. Is that something PIP told you to do? Thank you again. I hope we can figure this out.

I think all the problems I'm experiencing have something to do with this same PIP issue. It looks like on a variety of requests (from PIP, and then from URLLIB), I get "failed to verify local certificate issuer" or something along those lines.

Googling that error led me to add trusted-hosts to PIP which fixed the first issue. Then, on trying to check_internet, the request fails for the same reason. As does installing other packages and fetching things.

I am able to get to the "Apt Install" section by changing requests.get() references to requests.get(verify=False).

I'm wondering if my debian install was corrupt. I pulled it from the netinst ISO fresh from their website. I only installed the base system, no GUI along with web server & ssh server as well as "base system utilities". But for whatever reason, that resulted in certificate stuff being sorta locked down....not sure what causes the issue but[ here's some reading on it](https://jhooq.com/pip-install-connection-error/)

UPDATE: Yep, I've been able to get Demon Linux installed by simply forcing all code to turn off SSL verification

**Comment by Haquor** [comment]
Tried with a totally fresh Debian installation from latest Debian 11, codenamed bullseye, netinst, for 64-bit PC (amd64).
It's running on VMWare Player with a 40 GB HD, 6 allocated procs and 4 GB of RAM.
The only option select on the "software selection" screen is "Standard system utilities".
No SSH, no web browser, no desktop environment.

Some notes:
1. sudo must be installed from this state with apt install sudo
2. when running ./setup.py the first errors are encountered. Installing PIP packages fails.
![image](https://user-images.githubusercontent.com/737837/203690597-806c5c3e-00ee-40c9-892c-e2676549d844.png)
This is due to the aforementioned SSL error.

**Comment by Haquor** [comment]
This was a firewall issue, and its been solved. Thank you for your hasty response! The project is badass @RackunSec
